//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DoctorValue.java
//  @ Date : 2019-12-02
//  @ Author : 
//
//

package ClassStyle;


public class DoctorValue extends PersonValue {
	
	public DoctorValue() {
		age=30;
		name="Mr.Kim";
	}
	public void treat() {
	System.out.println("의사가 치료합니다");
	}
}
