//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HospitalExample.java
//  @ Date : 2019-12-02
//  @ Author : 
//
//


package ClassStyle;

public class HospitalExample {
	public static void main(String[] args) {
	
		PersonValue pv = new PersonValue();
		DoctorValue dv = new DoctorValue();
		NurseValue nv = new NurseValue();
		PatientValue pav = new PatientValue();
		
		//일반화 스타일. 상속 받은 것을 그대로 사용.
		
		System.out.println("Person Info : " + pv.getInfo());
		System.out.println("Doctor Info : " + dv.getInfo());
		System.out.println("Nurse Info : " + nv.getInfo());
		System.out.println("Patient Info : " + pav.getInfo());	
		
		
	}
}
