//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NurseValue.java
//  @ Date : 2019-12-02
//  @ Author : 
//
//

package ClassStyle;


public class NurseValue extends PersonValue {
	
	public NurseValue(){
		age=45;
		name="Mr.Ahn";
	}
	
	public void care() {
	System.out.println("간호사가 케어합니다");
	}
}
