//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PatirentValue.java
//  @ Date : 2019-12-02
//  @ Author : 
//
//

package ClassStyle;


public class PatientValue extends PersonValue {
	
	public PatientValue(){
		age=64;
		name="Mr.Park";
	}
	
	public void getTreat() {
	System.out.println("환자가 치료받습니다");
	}
}
