//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentSample.java
//  @ Date : 2019-11-27
//  @ Author : 
//
//


package whatIsClass;


public class StudentSample2 {
	public static void main(String[] args) {
	
	Student shion1 = new Student(); 	// 객체 인스턴스 바람직한 방법
	Student shion2 = new Student();
	
	System.out.println(shion1);
	System.out.println(shion2);
	
	if(shion1.equals(shion2))
		System.out.println("두 객체는 같다");
	else
		System.out.println("두 객체는 다르다");
	
	if(shion1 != shion2)
		System.out.println("두 객체는 달라달라");
	else
		System.out.println("두 객체는 같아");
	}
}
