//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentSample.java
//  @ Date : 2019-11-27
//  @ Author : 
//
//


package whatIsClass;


public class StudentSample {
	public static void main(String[] args) {
	/* case1 : 객체 변수 선언
	   Student shion;
	 
	   case 2 : 객체 변수 선언
	   Student shion = null;
	   shion = new Student();
	   
	   case1, case2 는 선언된 객체 변수를 인스턴스화해서 생성하는 것. new(객체 생성 연산자)
	   
	   case 3 : 객체 변수 인스턴스 생성
	   Student shion = new Student();
	 */
		
	Student shion = new Student(); 	// 객체 인스턴스 바람직한 방법
	// 구현된 처리로직을 호출
	shion.setName("홍길동");
	shion.setScore(90);
	shion.printScore();
	
	
	
	}
}
